<?php

/**
 * @file
 * Formball page and game elements
 */

/**
 * Implements hook_menu()
 */

function formball_game_menu() {
  $items['game'] = array(
    'title' => 'Formball Game',
    'description' => 'Page and elements of the game',
    'page callback' => 'formball_game_elements',
    'access callback' => TRUE,
  );

  return $items;
}

function formball_game_elements() {
  $build = array(
    'header' => array(
      '#type' => 'markup',
      '#markup' => 'Here goes the game elements',
    ),
    'game_table' => drupal_get_form('game_elements_form'),
  );
  return $build;
}

function game_elements_form ($form, &$form_submit) {

  $options = array();

  /* create checkboxes for player A and B */
  $players = array('A', 'B');
  foreach ($players as $player){
    for ($i=0; $i<9; $i++) {
      for($j=0; $j<9; $j++) {
        $row = $i + 1;
        $column = $j + 1;
        $key = 'player_' . $player . '_' . $row . '_' . $column;
        $form[$key] = array(
          '#title' => '',
          '#type' => 'checkbox',
        );

      }
    }
  }

  /* create ball positions on the field */

  for ($i=0; $i<9; $i++) {
    for ($j = 0; $j < 9; $j++) {
      $options[] = 0; /* CONTINUE HERE */
    }
  }

  $form['ball'] = array(
    '#title' => '',
    '#type' => 'radios',
    '#default_value' => variable_get('comment_preview', 1),
    '#options' => drupal_map_assoc(range(1,18)),
      '#attributes' => array(
        'class' => array(),
      ),
  );
  return $form;
}