<?php

/**
 * @file
 * Formball logo
 */

/**
 * Implements hook_block_info()
 */

function formball_logo_block_info(){
  $blocks['formball_logo'] = array (
    'info' => t('Formball Logo'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view()
 */

function formball_logo_block_view($delta = '') {
  $block = array();
  $block['subject'] = t('Formball Logo');
  $block['content'] = formball_logo_markup();
  return $block;
}


/**
 * Logo Markup
 */

function formball_logo_markup() {

  $logo_markup = '
     <div class="logo-grid-container">
        <div class="logo-row">
            <div class="logo-box">
                <div class="logo-unit-1-1"></div>
            </div>
            <div class="logo-box">
                <div class="logo-unit-1-2"></div>
            </div>
            <div class="logo-box">
                <div class="logo-unit-1-3">
                    <div class="logo-triangle"></div>
                </div>
            </div>
        </div>

        <div class="logo-row">
            <div class="logo-box">
                <div class="logo-unit-2-1"></div>
            </div>
            <div class="logo-box">
                <div class="logo-unit-2-2"></div>
            </div>
            <div class="box">
                <div class="logo-unit-2-3"></div>
            </div>
        </div>

        <div class="logo-row">
            <div class="logo-box">
                <div class="logo-unit-3-1"></div>
            </div>
            <div class="logo-box">
                <div class="logo-unit-3-2"></div>
            </div>
            <div class="logo-box">
                <div class="logo-unit-3-3">
                </div>
            </div>
        </div>

        <div class="logo-row">
            <div class="logo-box">
                <div class="logo-unit-4-1"></div>
            </div>
            <div class="logo-box">
                <div class="logo-unit-4-2"></div>
            </div>
            <div class="logo-box">
                <div class="logo-unit-4-3"></div>
            </div>
        </div>

        <div class="logo-row">
            <div class="logo-box">
                <div class="logo-unit-5-1"></div>
            </div>
            <div class="logo-box">
                <div class="logo-unit-5-2"></div>
            </div>
            <div class="logo-box">
                <div class="logo-unit-5-3"></div>
            </div>
        </div>

    </div>
  ';

  $build = array(
    'logo markup' => array(
      '#type' => 'markup',
      '#markup' => $logo_markup,
    ),
  );
  return $build;
}

